# Generated by Django 3.1.14 on 2022-02-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220205_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
