# Generated by Django 3.1.14 on 2022-02-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_todo_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日付/締切'),
        ),
    ]
