# Generated by Django 3.1.14 on 2022-02-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220212_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deleted_at',
        ),
    ]
