# Generated by Django 3.1.14 on 2022-02-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_todo_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date'),
        ),
        migrations.AddField(
            model_name='todo',
            name='field_1',
            field=models.TextField(blank=True, verbose_name='ゴミ箱'),
        ),
    ]
