# Generated by Django 3.1.14 on 2022-03-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220216_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日時'),
        ),
    ]
